let power=false,selected='',playing=false,paused=false,n=0,elapsed=0,last=0,raf=null,audio=null,gain=null,osc=null;const $=s=>document.querySelector(s),body=document.body;
function status(t){$('#status').textContent=t}
function ensureAudio(){if(!audio){audio=new(window.AudioContext||window.webkitAudioContext)();gain=audio.createGain();gain.gain.value=.055;gain.connect(audio.destination)}if(audio.state==='suspended')audio.resume()}
function tone(on){if(osc){try{osc.stop()}catch{}osc=null}if(!on)return;ensureAudio();osc=audio.createOscillator();osc.type='triangle';osc.frequency.value=selected.includes('Rock')?110:selected.includes('Rom')?220:165;const g=audio.createGain();g.gain.value=.035;osc.connect(g);g.connect(gain);osc.start()}
function resetVU(){$('.nl').style.transform=$('.nr').style.transform='rotate(-30deg)'}
function render(){n=Math.floor(elapsed*1.65);$('.counter').textContent=String(n).padStart(3,'0').slice(-3)}
function loop(now){if(!playing)return;if(!last)last=now;elapsed+=(now-last)/1000;last=now;const pulse=(Math.sin(now/105)+1)/2;$('.nl').style.transform='rotate('+(-30+pulse*39+Math.random()*12)+'deg)';$('.nr').style.transform='rotate('+(-30+pulse*35+Math.random()*15)+'deg)';render();raf=requestAnimationFrame(loop)}
function stopPlayback(reset=false){playing=false;paused=false;body.classList.remove('playing');cancelAnimationFrame(raf);raf=null;last=0;tone(false);resetVU();if(reset){elapsed=0;render()}}
function press(a){const b=$('[data-act="'+a+'"]');b?.classList.add('active');setTimeout(()=>b?.classList.remove('active'),160)}
function act(a){press(a);if(a==='power'){power=!power;body.classList.toggle('on',power);if(!power){stopPlayback(true);status('RetroTape desligado')}else{ensureAudio();status('RetroTape ligado · escolha uma fita')}return}if(!power){status('Ligue o POWER primeiro');return}
if(a==='play'){if(!selected){status('Escolha uma fita na biblioteca');return}if(playing)return;ensureAudio();playing=true;paused=false;last=0;body.classList.add('playing');tone(true);status('▶ '+selected+' · tocando');raf=requestAnimationFrame(loop)}
if(a==='pause'){if(!selected)return;if(playing){playing=false;paused=true;body.classList.remove('playing');cancelAnimationFrame(raf);raf=null;last=0;tone(false);resetVU();status('Ⅱ '+selected+' · pausado')}else if(paused){act('play')}}
if(a==='stop'){stopPlayback(true);status(selected?'■ '+selected+' · parada':'Escolha uma fita')}
if(a==='rew'){stopPlayback(false);elapsed=Math.max(0,elapsed-15);render();body.classList.add('rewinding');status('◀◀ rebobinando '+selected);setTimeout(()=>body.classList.remove('rewinding'),650)}
if(a==='ff'){stopPlayback(false);elapsed+=15;render();body.classList.add('fastforward');status('▶▶ avançando '+selected);setTimeout(()=>body.classList.remove('fastforward'),650)}
if(a==='eject'){stopPlayback(true);selected='';body.classList.remove('loaded');body.classList.add('ejecting');status('EJECT · fita removida');setTimeout(()=>body.classList.remove('ejecting'),500)}}
document.querySelectorAll('[data-act]').forEach(b=>b.addEventListener('click',()=>act(b.dataset.act)));
document.querySelectorAll('[data-tape]').forEach(b=>b.addEventListener('click',()=>{if(!power){status('Ligue o POWER primeiro');return}stopPlayback(true);selected=b.dataset.tape;$('.flyLabel').textContent=selected;body.classList.remove('ejecting','loaded');void body.offsetWidth;body.classList.add('inserting');status('Inserindo '+selected+'...');setTimeout(()=>{body.classList.remove('inserting');body.classList.add('loaded');status('Fita inserida: '+selected+' · pressione PLAY')},1250)}));
document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();act(playing?'pause':'play')}if(e.key==='Escape')act('stop')});render();